services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  service:
    image: service-image
    container_name: service
    build: .
    env_file: .env
    environment:
      POSTGRES_HOST: db
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: